#!/system/bin/sh
# ═══════════════════════════════════════════════════════════════
# PrimeThermal vY.1.2-ArtisanROM — User Configuration
# Supported: SM-G970F (S10e) · SM-G973F (S10) · SM-G975F (S10+)
# Edit this file to customise module behaviour.
# Changes take effect on next reboot (module re-sources this file).
# ═══════════════════════════════════════════════════════════════

# ── Operating mode ─────────────────────────────────────────────
# auto      → normal adaptive logic (recommended)
# gaming    → forces GAMING clocks whenever screen is on
# powersave → caps all clusters at 60 % (battery-critical)
MODE=auto

# ── Logging ────────────────────────────────────────────────────
ENABLE_LOG=true

# ── Gaming Mode — package list (Encore + PrimeThermal merged) ──
# Space-separated package names. When ANY is in the foreground
# (auto mode only), PrimeThermal enters GAMING mode.
GAMING_PACKAGES="
  Nekootan.kfkj
  adventure.rpg.anime.game.vng.ys6
  age.of.civilizations2.jakowski.lukasz
  air.com.ubisoft.brawl.halla.platform.fighting.action.pvp
  brownmonster.app.game.rushrally3
  com.AlfaBravo.Combat
  com.CarXTech.highWay
  com.CarXTech.street
  com.ChillyRoom.DungeonShooter
  com.EndlessClouds.Treeverse
  com.EtherGaming.PocketRogues
  com.Flanne.MinutesTillDawn.roguelike.shooting.gp
  com.FosFenes.Sonolus
  com.GameCoaster.ProtectDungeon
  com.HoYoverse.Nap
  com.HoYoverse.hkrpgoversea
  com.LanPiaoPiao.PlantsVsZombiesRH
  com.Nekootan.kfkjos.google
  com.MOBGames.PoppyMobileChap1
  com.OxGames.Pluvia
  com.PigeonGames.Phigros
  com.PigeonGames.Rizline
  com.ProjectMoon.LimbusCompany
  com.Psyonix.RL2D
  com.RickyG.DONTFORGET
  com.RoamingStar.BlueArchive
  com.ShinyShoe.MonsterTrain.mtap
  com.Shooter.ModernWarfront
  com.Shooter.ModernWarship
  com.Shooter.ModernWarships
  com.Sunborn.SnqxExilium
  com.Sunborn.SnqxExilium.Glo
  com.TeamCherry.HollowKnight
  com.TechTreeGames.TheTower
  com.Vince.AlamobileFormula
  com.WandaSoftware.TruckersofEurope3
  com.Wispwood.ArrowQuest
  com.YoStarEN.Arknights
  com.YoStarEN.HBR
  com.YoStarEN.MahjongSoul
  com.YoStarEN.StellaSora
  com.YoStarJP.MajSoul
  com.YoStar.AetherGazer
  com.YostarJP.BlueArchive
  com.YoStarJP.Arknights
  com.ZeroCastleGameStudioINTL.StrikeBusterPrototype
  com.ZeroCastleGameStudio.StrikeBusterPrototype
  com.actgames.bbee
  com.activision.callofduty.shooter
  com.activision.callofduty.warzone
  com.albiononline
  com.aligames.kuang.kybc
  com.aligames.kuang.kybc.huawei
  com.alightcreative.motion
  com.and.games505.Terraria
  com.and.games505.TerrariaPaid
  com.archosaur.sea.dr.gp
  com.asobimo.toramonline
  com.autumn.skullgirls
  com.axlebolt.standoff2
  com.bairimeng.dmmdzz
  com.bandainamcoent.opbrww
  com.bandainamcoent.sao
  com.bandainamcoent.shinycolorsprism
  com.bandainamcoent.tensuramrkww
  com.bandainamcoent.ultimateninjastorm
  com.bandainamcogames.dbzdokkanww
  com.bandainamcoent.dblegends_ww
  com.bandainamcoent.idolmaster_gakuen
  com.bandainamcoent.imas_millionlive_theaterdays
  com.bf.sgs.hdexp.bd
  com.bhvr.deadbydaylight
  com.bilibiligame.heglgp
  com.bilibili.azurlane
  com.bilibili.deadcells.mobile
  com.bilibili.fatego
  com.bilibili.heaven
  com.bilibili.priconne
  com.bilibili.star.bili
  com.bilibili.warmsnow
  com.biligamekr.aggp
  com.bingkolo.kleins.cn
  com.blizzard.diablo.immortal
  com.blizzard.wtcg.hearthstone
  com.bluepoch.m.en.reverse1999
  com.bscotch.crashlands2
  com.bushiroad.d4dj
  com.bushiroad.en.bangdreamgbp
  com.bushiroad.lovelive.schoolidolfestival2
  com.carxtech.sr
  com.chillyroom.soulknightprequel
  com.chucklefish.stardewvalley
  com.citra.emu
  com.com2us.starseedgl.android.google.global.normal
  com.companyname.AM2RWrapper
  com.criticalforceentertainment.criticalops
  com.crunchyroll.princessconnectredive
  com.denachina.g13002010
  com.dena.a12026801
  com.devsisters.ck
  com.dfjz.moba
  com.dgames.g15002002
  com.dishii.mm
  com.dishii.soh
  com.dois.greedgame
  com.dolphinemu.dolphinemu
  com.dragonli.projectsnow.lhm
  com.drivezone.car.race.game
  com.dts.freefireadv
  com.dts.freefiremax
  com.dts.freefireth
  com.dts.freefireth.huawei
  com.ea.gp.apexlegendsmobilefps
  com.ea.gp.fifamobile
  com.ea.gp.nfsm
  com.ea.game.nfs14_row
  com.ea.games.r3_row
  com.ea.game.pvz2_rfl
  com.ea.game.pvz2_row
  com.ea.game.pvzfree_row
  com.epicgames.fortnite
  com.epicgames.portal
  com.eyougame.msen
  com.fantablade.icey
  com.farlightgames.igame.gp
  com.feralinteractive.gridas
  com.feralinteractive.gridautosport_edition_android
  com.firsttouchgames.dls7
  com.fizzd.connectedworlds
  com.gabama.monopostolite
  com.gaijingames.wtm
  com.gameark.ggplay.lonsea
  com.gamedevltd.wwh
  com.gameloft.android.ANMP.GloftA9HM
  com.gameloft.android.ANMP.GloftMVHM
  com.gameloft.android.SAMS.GloftA9SS
  com.garena.game.codm
  com.garena.game.df
  com.garena.game.kgid
  com.garena.game.kgtw
  com.garena.game.kgvn
  com.garena.game.lmjx
  com.garena.game.nfsm
  com.gbits.funnyfighter.android.overseas
  com.gravity.romg
  com.gravity.roo.sea
  com.gryphline.endfield
  com.gryphline.endfield.gp
  com.gryphline.exastris.gp
  com.guigugame.guigubahuang
  com.halo.windf.hero
  com.heavenburnsred
  com.hermes.j1game
  com.hermes.mk
  com.herogame.gplay.magicminecraft.mmorpg
  com.hg.cosmicshake
  com.hg.lbw
  com.hottagames.nte
  com.hottapkgs.hotta
  com.hypergryph.arknights
  com.hypergryph.exastris
  com.idreamsky.klbqm
  com.idreamsky.strinova
  com.igg.android.doomsdaylastsurvivors
  com.ilongyuan.implosion
  com.infoldgames.infinitynikkien
  com.japan.datealive.gp
  com.je.supersus
  com.jumpw.mobile300
  com.kakaogames.eversoul
  com.kakaogames.gdts
  com.kakaogames.wdfp
  com.kiloo.subwaysurf
  com.kog.grandchaseglobal
  com.komoe.kmumamusumegp
  com.kurogame.aki
  com.kurogame.gplay.punishing.grayraven.en
  com.kurogame.haru
  com.kurogame.haru.bilibili
  com.kurogame.haru.hero
  com.kurogame.mingchao
  com.kurogame.wutheringwaves.global
  com.leiting.wf
  com.lemcnsun.soultide.android
  com.levelinfinite.hotta.gp
  com.levelinfinite.sgameGlobal
  com.levelinfinite.sgameGlobal.midaspay
  com.lilithgames.hgame.cn
  com.lilithgame.hgame.gp
  com.lilithgame.roc.gp
  com.linecorp.LGGRTHN
  com.linegames.sl
  com.longe.allstarhmt
  com.lrgame.dldl.sea
  com.madfingergames.legends
  com.maleo.bussimulatorid
  com.miHoYo.GI.samsung
  com.miHoYo.GenshinImpact
  com.miHoYo.HSoDv2JPOriginalEx
  com.miHoYo.Honkai3rd
  com.miHoYo.Nap
  com.miHoYo.Yuanshen
  com.miHoYo.bh3
  com.miHoYo.bh3global
  com.miHoYo.bh3oversea
  com.miHoYo.bh3oversea_vn
  com.miHoYo.bh3rdJP
  com.miHoYo.bh3.bilibili
  com.miHoYo.bh3.mi
  com.miHoYo.bh3.uc
  com.miHoYo.enterprise.NGHSoD
  com.miHoYo.hkrpg
  com.miHoYo.ys
  com.miHoYo.zenless
  com.minidragon.idlefantasy
  com.miraclegames.farlight84
  com.mobile.legends
  com.mobilelegends.hwag
  com.mobilelegends.mi
  com.mojang.hostilegg
  com.mojang.minecraftpe
  com.mojang.minecraftpe.patch
  com.morizero.milthm
  com.nanostudios.games.twenty.minutes
  com.ncsoft.lineagen
  com.nebulajoy.act.dmcpoc.asia
  com.nekki.shadowfight
  com.nekki.shadowfight3
  com.neowizgames.game.browndust2
  com.neowiz.game.idolypride.en
  com.netease.AVALON
  com.netease.EVE
  com.netease.aceracer
  com.netease.allstar
  com.netease.dfjs
  com.netease.dunkcd
  com.netease.dwrg
  com.netease.eve.en
  com.netease.frxyna
  com.netease.g78na.gb
  com.netease.g93na
  com.netease.h73hmt
  com.netease.h75na
  com.netease.hyxd
  com.netease.idv
  com.netease.ko
  com.netease.l22
  com.netease.lagrange
  com.netease.letsplayen
  com.netease.lglr
  com.netease.lztgglobal
  com.netease.moba
  com.netease.mrzh
  com.netease.newspike
  com.netease.nshm
  com.netease.onmyoji
  com.netease.party
  com.netease.partyglobal
  com.netease.pes
  com.netease.race
  com.netease.sky
  com.netease.soulofhunter
  com.netease.tj
  com.netease.tom
  com.netease.wotb
  com.netease.x19
  com.netease.yhtj
  com.netflix.NGP.GTAIIIDefinitiveEdition
  com.netflix.NGP.GTASanAndreasDefinitiveEdition
  com.netflix.NGP.GTAViceCityDefinitiveEdition
  com.netmarble.skiagb
  com.netmarble.sololv
  com.netmarble.tog
  com.nexon.bluearchive
  com.nexon.kartdrift
  com.nexon.konosuba
  com.nexon.mdnf
  com.nexon.mod
  com.ngame.allstar.eu
  com.nianticlabs.monsterhunter
  com.nianticproject.ingress
  com.noctuagames.android.ashechoes
  com.npixel.GranSagaGB
  com.olzhass.carparking.multyplayer
  com.papegames.infinitynikki
  com.papegames.nn4.en
  com.pearlabyss.blackdesertm
  com.pearlabyss.blackdesertm.gl
  com.pinkcore.tkfm
  com.plarium.raidlegends
  com.playdigious.deadcells.mobile
  com.play.rosea
  com.proximabeta.dn2.global
  com.proximabeta.mf.aceforce2
  com.proximabeta.mf.uamo
  com.proximabeta.nikke
  com.proxima.dfm
  com.prpr.musedash
  com.pubg
  com.pubg.imobile
  com.pubg.krmobile
  com.pubg.newstate
  com.pwrd.hotta.laohu
  com.pwrd.opmwsea
  com.pwrd.p5x
  com.r2games.myhero.bilibili
  com.rayark.cytus2
  com.rayark.deemo2
  com.rayark.deemoreborn
  com.rayark.implosion
  com.rayark.sdorica
  com.retroarch
  com.riotgames.league.teamfighttactics
  com.riotgames.league.teamfighttacticstw
  com.riotgames.league.teamfighttacticsvn
  com.riotgames.league.wildrift
  com.roblox.client
  com.roblox.client.vnggames
  com.robtopx.geometryjump
  com.rockstargames.gta3
  com.rockstargames.gta3.de
  com.rockstargames.gtasa
  com.rockstargames.gtasa.de
  com.rockstargames.gtavc
  com.rockstargames.gtavc.de
  com.rsg.myheroesen
  com.sandboxinteractive.albiononline
  com.sega.ColorfulStage.en
  com.sega.pjsekai
  com.sega.soniccd.classic
  com.shatteredpixel.shatteredpixeldungeon
  com.shenlan.m.reverse1999
  com.silverstarstudio.angellegion
  com.smokoko.race
  com.sofunny.Sausage
  com.soulgamechst.majsoul
  com.spaceapegames.beatstar
  com.squareenix.lis
  com.starform.metalstorm
  com.stove.epic7.google
  com.studiobside.CounterSide
  com.studiowildcard.wardrumstudios.ark
  com.sunborn.girlsfrontline.en
  com.sunborn.neuralcloud
  com.sunborn.neuralcloud.en
  com.supercell.boombeach
  com.supercell.brawlstars
  com.supercell.clashofclans
  com.supercell.clashroyale
  com.supercell.hayday
  com.supercell.squad
  com.t2ksports.nba2k20and
  com.tencent.KiHan
  com.tencent.af
  com.tencent.ig
  com.tencent.iglite
  com.tencent.letsgo
  com.tencent.lolm
  com.tencent.mf.uam
  com.tencent.msgame
  com.tencent.nba2kx
  com.tencent.tmgp.WePop
  com.tencent.tmgp.bh3
  com.tencent.tmgp.cf
  com.tencent.tmgp.cod
  com.tencent.tmgp.dfjs
  com.tencent.tmgp.dfm
  com.tencent.tmgp.dnf
  com.tencent.tmgp.dwrg
  com.tencent.tmgp.gnyx
  com.tencent.tmgp.kr.codm
  com.tencent.tmgp.pubgmhd
  com.tencent.tmgp.sgame
  com.tencent.tmgp.sgamece
  com.tencent.tmgp.speedmobile
  com.tencent.tmgp.sskeus
  com.tencent.tmgp.wuxia
  com.tencent.toaa
  com.tgc.sky.android
  com.the10tons.dysmantle
  com.tinybuildgames.helloneighbor
  com.tipsworks.android.pascalswager
  com.trampolinetales.lbal
  com.ubisoft.rainbowsixmobile.r6.fps.pvp.shooter
  com.valvesoftware.cswgsm
  com.valvesoftware.source
  com.vng.mlbbvn
  com.vng.pubgmobile
  com.vng.speedvn
  com.winlator
  com.winlator.cmod
  com.wondergames.warpath.gp
  com.xd.TLglobal
  com.xd.muffin.gp.global
  com.xd.rotaeno.googleplay
  com.xd.rotaeno.tapcn
  com.xd.ssrpgen
  com.xd.terraria
  com.xindong.torchlight
  com.yinhan.hunter
  com.yongshi.tenojo
  com.yoozoo.jgame.global
  com.yoozoo.jgame.us
  com.zlongame.mhmnz
  com.ztgame.bob
  com.ztgame.yyzy
  cyou.joiplay.joiplay
  game.qualiarts.idolypride
  gplay.punishing.grayraven
  jp.co.bandainamcoent.BNEI0242
  jp.co.craftegg.band
  jp.co.cygames.princessconnectredive
  jp.co.cygames.umamusume
  jp.co.koeitecmo.ReslerianaGL
  jp.konami.duellinks
  jp.konami.masterduel
  jp.konami.pesam
  jp.pokemon.pokemonunite
  jp.goodsmile.touhoulostwordglobal_android
  me.mugzone.emiria
  me.pou.app
  me.tigerhix.cytoid
  moe.low.arc
  net.kdt.pojavlaunch
  net.kdt.pojavlaunch.debug
  net.kdt.pojavlaunch.firefly
  net.wargaming.wot.blitz
  org.citra.emu
  org.dolphinemu.dolphinemu
  org.flos.phira
  org.godotengine.godot4
  org.ppsspp.ppsspp
  org.ppsspp.ppssppgold
  org.vita3k.emulator
  org.citron.citron_emu
  org.sudachi.sudachi_emu.ea
  org.uzuy.uzuy_emu.ea
  org.yuzu.yuzu_emu
  ru.unisamp_mobile.game
  sh.ppy.osulazer
  skyline.emu
  tw.sonet.princessconnect
  tw.txwy.and.arknights
  vng.games.revelation.mobile
  xyz.aethersx2.android
"

# ── Gaming Mode — thermal soft cap ─────────────────────────────
GAMING_IGNORE_THERMAL=false
GAMING_THERMAL_CEIL=48

# ── Gaming Mode — hard abort temperature ───────────────────────
GAMING_HARD_ABORT=54

# ── Gaming Mode — minimum frequency floor ──────────────────────
# Locks each cluster's scaling_min_freq to this % of stock max
# during GAMING. Prevents inter-frame frequency droops.
# 0 = disable (reset to cpuinfo_min_freq). Default: 50.
GAMING_MIN_FLOOR_PCT=50

# ── Thermal trigger temperatures (°C) ──────────────────────────
TEMP_AUTO_TRIGGER=42
TEMP_GAMING_TRIGGER=45
TEMP_SAVE_TRIGGER=38

# ── Burst detection threshold ───────────────────────────────────
# Instant ACTIVE when single-tick load >= this %. Default: 25.
BURST_THRESH=25

# ── Loop timing ────────────────────────────────────────────────
# Sleep between ticks (s). Actual cycle = LOOP_SLEEP + 1.
LOOP_SLEEP=4

# ── SurfaceFlinger latency tweaks ──────────────────────────────
ENABLE_SF_TWEAKS=true

# ── I/O scheduler tuning ───────────────────────────────────────
ENABLE_IO_TUNING=true

# ── sched_boost (Samsung EAS) ──────────────────────────────────
ENABLE_SCHED_BOOST=true

# ── Android Game Manager API (Android 12+) ─────────────────────
ENABLE_GAME_CMD=true

# ─── WebUI persistent overrides (do not edit below this line) ──
